name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo fmt -- --check
      - run: cargo test --all-features
      - run: cargo test --all-features --doc
      - run: cargo clippy --all-targets --all-features --locked -- -D warnings
      - run: cargo publish --dry-run
